export const CATEGORYDATA_REQUEST = "CATEGORYDATA_REQUEST";
export const CATEGORYDATA_SUCCESS = "CATEGORYDATA_SUCCESS";
export const CATEGORYDATA_FAILS = "CATEGORYDATA_FAILS";

export const SUB_CATEGORYDATA_REQUEST = "SUB_CATEGORYDATA_REQUEST";
export const SUB_CATEGORYDATA_SUCCESS = "SUB_CATEGORYDATA_SUCCESS";
export const SUB_CATEGORYDATA_FAILS = "SUB_CATEGORYDATA_FAILS";

export const SERVICES_REQUEST = "SERVICES_REQUEST";
export const SERVICES_SUCCESS = "SERVICES_SUCCESS";
export const SERVICES_FAILS = "SERVICES_FAILS";

export const ACTIVITY_REQUEST = "ACTIVITY_REQUEST";
export const ACTIVITY_SUCCESS = "ACTIVITY_SUCCESS";
export const ACTIVITY_FAILS = "ACTIVITY_FAILS";


export const ADDRESS_SEND_REQUEST = "ADDRESS_SEND_REQUEST";
export const ADDRESS_SEND_SUCCESS = "ADDRESS_SEND_SUCCESS";
export const ADDRESS_SEND_FAILS = "ADDRESS_SEND_FAILS";

export const EDIT_REQUEST = "EDIT_REQUEST";
export const EDIT_SUCCESS = "EDIT_SUCCESS";
export const EDIT_FAILS = "EDIT_FAILS";